language:
    - java


jdk:
  - oraclejdk8
  - openjdk7

before_install:
  - cd test\java\test\java
  
services:
    - mysql

script:
  - ant VerificacionTest

sudo:
    - false

notifications:
    - email: false  # Desactivamos las notificaciones por email para evitar spam