language:
    - java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
 
services:
  - mysql

script:
  - mvn test -f pom.xml
  - mvn clean compile assembly:single
 

deploy:
  provider: releases
  api_key: 19ad4f666fe157279992d9d0848849d8e244e66e
  file: /home/travis/build/EGC-1617/Verificacion-G1/target/Verificacion1.jar
  skip_cleanup: true
  on:
    public_repo: EGC-1617/Verificacion-G1
    tags: false
    branch: master	
sudo:
    - false

notifications:
    - email: false  # Desactivamos las notificaciones por email para evitar spam