language:
    - java


jdk:
  - oraclejdk8
  - openjdk7

before_install:
  - cd test
  - cd java
  - cd test
  - cd java
  
services:
    - mysql

script:
  - ant VerificacionTest

sudo:
    - false

notifications:
    - email: false  # Desactivamos las notificaciones por email para evitar spam