language:
    - java


jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
 
services:
  - mysql

script:
  - mvn test -f pom.xml
  - mvn clean compile assembly:single
  
deploy:
    provider: releases
    api_key:
        secure: 1b4dbc53ea4688a352b81b771819d0cb377bedba 
    file:
        - target/Verificacion1.jar

    skip_cleanup: true
    on:
        repo: EGC-1617/Verificacion-G1
        tags: true

sudo:
    - false

notifications:
    - email: false  # Desactivamos las notificaciones por email para evitar spam