language:
    - java


jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
 
services:
    - mysql

script:
  - mvn test -f pom.xml

sudo:
    - false

notifications:
    - email: false  # Desactivamos las notificaciones por email para evitar spam