language:
    - java


jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
 
services:
  - mysql

script:
  - mvn test -f pom.xml
  - mvn clean compile assembly:single
  
deploy:
    provider: releases
    api_key: 5b231acf13b0e7b22c6256f9e704621dfa47e9db 
    file:
        - /home/travis/build/EGC-1617/Verificacion-G1/target/Verificacion1.jar

    skip_cleanup: true
    on:
        repo: EGC-1617/Verificacion-G1
        tags: false
        branch: master
		
sudo:
    - false

notifications:
    - email: false  # Desactivamos las notificaciones por email para evitar spam